    <option value="">Ninguno</option>
    <option value="albania">Albania</option>
    <option value="alemania">Alemania</option>
    <option value="andorra">Andorra</option>
    <option value="austria">Austria</option>
    <option value="bélgica">Bélgica</option>
    <option value="bielorrusia">Bielorrusia</option>
    <option value="bosnia">Bosnia y Herzegovina</option>
    <option value="bulgaria">Bulgaria</option>
    <option value="croacia">Croacia</option>
    <option value="dinamarca">Dinamarca</option>
    <option value="eslovaquia">Eslovaquia</option>
    <option value="eslovenia">Eslovenia</option>
    <option value="españa">España</option>
    <option value="estonia">Estonia</option>
    <option value="finlandia">Finlandia</option>
    <option value="francia">Francia</option>
    <option value="grecia">Grecia</option>
    <option value="hungría">Hungría</option>
    <option value="irlanda">Irlanda</option>
    <option value="islandia">Islandia</option>
    <option value="italia">Italia</option>
    <option value="letonia">Letonia</option>
    <option value="liechtenstein">Liechtenstein</option>
    <option value="lituania">Lituania</option>
    <option value="luxemburgo">Luxemburgo</option>
    <option value="malta">Malta</option>
    <option value="moldavia">Moldavia</option>
    <option value="mónaco">Mónaco</option>
    <option value="montenegro">Montenegro</option>
    <option value="noruega">Noruega</option>
    <option value="países-bajos">Países Bajos</option>
    <option value="polonia">Polonia</option>
    <option value="portugal">Portugal</option>
    <option value="reino-unido">Reino Unido</option>
    <option value="república-checa">República Checa</option>
    <option value="rumanía">Rumanía</option>
    <option value="rusia">Rusia</option>
    <option value="san-marino">San Marino</option>
    <option value="serbia">Serbia</option>
    <option value="suecia">Suecia</option>
    <option value="suiza">Suiza</option>
    <option value="ucrania">Ucrania</option>
